name: Common Makefile Setup
description: Installs my personal common Makefiles
# There were issues seen propagating CAVCROSBY_MAKEFILES_PATH from the composite
# action to the calling workflow. Using 'outputs' seemed to be a way to get
# around this and is considered "cleaner" design. For reference on a related
# issue and additional information: https://github.com/actions/runner/issues/789
outputs:
  CAVCROSBY_MAKEFILES_PATH:
    description: The install path to my personal common Makefiles
    value: ${{ steps.install-cavcrosby-makefiles.outputs.CAVCROSBY_MAKEFILES_PATH }}
runs:
  using: composite
  steps:
    - name: Grab cavcrosby-makefiles's official GPG key
      run: |
        curl --fail --show-error --location "https://packagecloud.io/cavcrosby/makefiles/gpgkey" \
          | sudo gpg --dearmor --output "/usr/share/keyrings/cavcrosby-makefiles-keyring.gpg"
      shell: sh

    - name: Add cavcrosby-makefiles's main apt repository
      run: |
        apt_sourceline="deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/cavcrosby-makefiles-keyring.gpg]
          https://packagecloud.io/cavcrosby/makefiles/$(lsb_release --id --short | tr '[:upper:]' '[:lower:]')
          $(lsb_release --codename --short) main"

        # leave var unquoted as I want typical word splitting to occur, for reference:
        # https://www.gnu.org/software/bash/manual/html_node/Word-Splitting.html
        echo ${apt_sourceline} | sudo tee "/etc/apt/sources.list.d/cavcrosby-makefiles.list"
      shell: sh
  
    - id: install-cavcrosby-makefiles
      name: Install cavcrosby-makefiles
      run: |
        sudo apt-get update
        sudo apt-get install --assume-yes \
          cavcrosby-makefiles

        . "/etc/profile.d/cavcrosby-makefiles"
        echo "::set-output name=CAVCROSBY_MAKEFILES_PATH::$(echo ${CAVCROSBY_MAKEFILES_PATH})"
      shell: sh
